# Generated by Django 4.2.1 on 2023-05-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('did', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluk', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taluk', to='home.district')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('aadhar', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('date_avail1', models.DateField()),
                ('date_avail2', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_center', to='home.district')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_center', to='home.taluk')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dose1', models.DateField()),
                ('dose2', models.DateField()),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vaccination', to='home.user')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='User_vaccine_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_vaccine_registration', to='home.user')),
                ('date_avail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vaccine_center')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
            ],
        ),
    ]
