# Generated by Django 4.2.1 on 2023-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_vaccination_dose2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='dose2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
