# Generated by Django 4.2.1 on 2023-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_vaccination_dose2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_center',
            name='date_avail1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine_center',
            name='date_avail2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
