# Generated by Django 4.2.1 on 2023-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_vaccine_center_date_avail1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='dose1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
